### ISSUE TITLE
Operator cannot work on kubernetes ver 1.8

### ISSUE THREAD

**Issue by mobilesfinks** [kbst/memcached#10]
On K8S documentation i found next info:

> ThirdPartyResource is deprecated as of Kubernetes 1.7 and has been removed in version 1.8 in accordance with the deprecation policy for beta features.

So, when you try start on k8s 1.8 you get error 
`error validating data: unknown object type schema.GroupVersionKind{Group:"extensions", Version:"v1beta1", Kind:"ThirdPartyResource"}; `

I take raw configuration and make changes how provides in documentation of K8S (https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/)

Operator was started, but this all. Nothing Memcache cluster started on default namespace
In operator pod i found errors
```
2017-11-13 18:16:00,173 ERROR PeriodicCheck (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 13 Nov 2017 18:16:00 GMT', 'Content-Length': '19', 'Content-Type': 'text/plain; charset=utf-8'})
HTTP response body: 404 page not found

Traceback (most recent call last):
  File "/opt/memcached_operator/memcached_operator/periodical.py", line 61, in check_existing
    cluster_list = memcached_tpr_api.list_memcached_for_all_namespaces()
  File "/opt/memcached_operator/memcached_operator/memcached_tpr_v1alpha1_api.py", line 109, in list_memcached_for_all_namespaces
    collection_formats=collection_formats)
  File "/root/.local/share/virtualenvs/memcached_operator-9z7oKIBd/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 328, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/root/.local/share/virtualenvs/memcached_operator-9z7oKIBd/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 152, in __call_api
    _request_timeout=_request_timeout)
  File "/root/.local/share/virtualenvs/memcached_operator-9z7oKIBd/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 351, in request
    headers=headers)
  File "/root/.local/share/virtualenvs/memcached_operator-9z7oKIBd/lib/python3.5/site-packages/kubernetes/client/rest.py", line 233, in GET
    query_params=query_params)
  File "/root/.local/share/virtualenvs/memcached_operator-9z7oKIBd/lib/python3.5/site-packages/kubernetes/client/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 13 Nov 2017 18:16:00 GMT', 'Content-Length': '19', 'Content-Type': 'text/plain; charset=utf-8'})
HTTP response body: 404 page not found
```

Need more serious editing than just the deploy configuration

Used configuration  
``` ---
apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  description: Managed Memcached clusters
  metadata:
    name: memcached.operator.kubestack.com
  spec:
    scope: Namespaced
    group: operator.kubestack.com
    version: v1
    names:
      kind: memcached
      plural: memcached
      singular: memcached

- apiVersion: v1
  kind: Namespace
  metadata:
    name: kubestack

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: memcached-operator
    namespace: kubestack

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: memcached-operator
  rules:
  - apiGroups:
    - operator.kubestack.com
    resources:
    - memcacheds
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - extensions
    resources:
    - thirdpartyresources
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - list
    - create
    - get
    - patch
    - delete
  - apiGroups:
    - extensions
    resources:
    - replicasets
    verbs:
    - list
    - get
    - delete
  - apiGroups:
    - ''
    resources:
    - services
    verbs:
    - list
    - create
    - get
    - patch
    - delete
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - list
    - create
    - get
    - patch
    - delete
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - list

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: memcached-operator
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: memcached-operator
  subjects:
  - kind: ServiceAccount
    name: memcached-operator
    namespace: kubestack

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      operator: memcached.operator.kubestack.com
      heritage: kubestack.com
    name: memcached-operator
    namespace: kubestack
  spec:
    replicas: 1
    selector:
      matchLabels:
        operator: memcached.operator.kubestack.com
    template:
      metadata:
        labels:
          operator: memcached.operator.kubestack.com
          heritage: kubestack.com
      spec:
        containers:
        - image: kubestack/memcached:v0.1.0
          name: memcached-operator
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
        serviceAccountName: memcached-operator

- apiVersion: operator.kubestack.com/v1
  kind: memcached
  metadata:
    name: memcached
    namespace: default
  spec:
    mcrouter:
      replicas: 1
      memcached_limit_cpu: 100m
      memcached_limit_memory: 128Mi
    memcached:
      replicas: 2
      memcached_limit_cpu: 100m
      memcached_limit_memory: 128Mi
```

**Comment by pst** [comment]
CRD support has been merged.
